experiment_name: deepdeformable_rgb_t01_split_code_point
logging_root: ./logs-lmk
summary_root: ./summaries-lmk
batch_size: 1
lr: 0.0001
epochs: 100
epochs_til_checkpoint: 50
steps_til_summary: 100
model_type: sine
latent_dim: 128
hidden_num: 128
num_hidden_layers: 3
hyper_hidden_layers: 1
checkpoint_path: ./model_dir/rgb_test15/checkpoints/model_final.pth
dir_caricshop: ./dataset/RGB3DCaricShop_raw_t_mesh
dir_caricature_data: ./dataset/data_81
